<a href="https://colab.research.google.com/github/TalitaBorg/Logica-de-Programacao/blob/main/matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#vetor

carros =["HRV", "Golf", "Focus", "Argo"]
carros.append("Pólo")
for i in carros:
  print(i)


HRV
Golf
Focus
Argo
Pólo


In [ ]:
#Matriz

carros = [
         ["Modelo", "HRV"],
         ["Fabricante", "Honda"],
         ["Ano", 2016]
]

#print(carros[2][1])
carros.append(["Cor", "Prata"])
for linha, coluna in carros:
  print("Linha: " + linha + "|"  + "Coluna: " + coluna)
  print(linha + "|"  + str(coluna))
#print(carros[3][0])



Cor


In [ ]:
A = [
    [1,2,3],
    [4,5,6]
]

B = [
    [4,5,6],
    [7,8,9]
]

Soma_matriz = []

#Somando elemento por elemento
for linhas in range(len(A)):
  linha = []
  for colunas in range(len(A[0])):
    soma = A[linhas][colunas] + B[linhas][colunas]
    linha.append(soma)
  Soma_matriz.append(linha)
print("Matriz soma: ")
for linha in Soma_matriz:
  print(linha)

Matriz soma: 
[-3, -3, -3]
[-3, -3, -3]


In [ ]:
# Multiplicação de matriz 2x3 por 3x2

# Matriz A (2x3)
A = [
    [1, 2, 3],
    [4, 5, 6]
]

# Matriz B (3x2)
B = [
    [7, 8],
    [9, 10],
    [11, 12]
]

# Matriz resultado (2x2)
resultado = [[0, 0],
             [0, 0]]

# Multiplicação de matrizes
for i in range(2):        # linhas de A
    for j in range(2):    # colunas de B
        for k in range(3):  # elementos comuns
            resultado[i][j] += A[i][k] * B[k][j]

# Exibir resultado
print("Matriz Resultante (2x2):")
for linha in resultado:
    print(linha)


Matriz Resultante (2x2):
[58, 64]
[139, 154]


In [ ]:
#Subtração de matrizes de mesma ordem
A = [
    [4,8],
    [10,12]
]

B = [
    [1,4],
    [8,5]
]

Subrai_matriz = []

#Subtraindo elemento por elemento
for linhas in range(len(A)):
  linha = []
  for colunas in range(len(A[0])):
    subtrai = A[linhas][colunas] - B[linhas][colunas]
    linha.append(subtrai)
  Subrai_matriz.append(linha)
print("Matriz subtração: ")
for linha in Subrai_matriz:
  print(linha)

Matriz subtração: 
[3, 4]
[2, 7]


In [ ]:
linhas = int(input("Digite o número de linhas da matriz: "))
colunas = int(input("Digite o número de colunas da matriz: "))

#Lendo a primeira matriz
print("Digite os elementos da matriz A: ")
A = []
for i in range(linhas):
  linha = []
  for j in range(colunas):
    valor = int(input(f"A[{i}][{j}]: "))
    linha.append(valor)
  A.append(linha)

#Lendo a segunda matriz
print("Digite os elementos da matriz B: ")
B = []
for i in range(linhas):
  linha = []
  for j in range(colunas):
    valor = int(input(f"B[{i}][{j}]: "))
    linha.append(valor)
  B.append(linha)

print(f"As matrizes são A: {A} e B: {B}")


Digite o número de linhas da matriz: 2
Digite o número de colunas da matriz: 2
Digite os elementos da matriz A: 
A[0][0]: 4
A[0][1]: 8
A[1][0]: 10
A[1][1]: 12
Digite os elementos da matriz B: 
B[0][0]: 1
B[0][1]: 4
B[1][0]: 8
B[1][1]: 5
As matrizes são A: [[4, 8], [10, 12]] e B: [[1, 4], [8, 5]]


In [ ]:
import numpy
A = numpy.array([4,8,10,12])
B = numpy.array([[4,8],[10,12]])
print(A)
print(B)

[ 4  8 10 12]
[[ 4  8]
 [10 12]]


In [ ]:
#soma com biblioteca Numpy
import numpy as np
A = np.array([[4,8],[10,12]])
B = np.array([[1,4],[8,5]])
soma = A+B
print(soma)


[[ 5 12]
 [18 17]]


In [ ]:
#Multiplicação com biblioteca Numpy
import numpy as np
A = np.array([[4,8],[10,12]])
B = np.array([[1,4],[8,5]])
multiplica = A*B
print(multiplica)

[[ 4 32]
 [80 60]]


In [ ]:
import numpy as np
A = np.array([[4,8],[10,12]])
elemento = A[0][1]
elemento1 = A[1][1]
print(elemento)
print(elemento1)

8
12
